# Generated by Django 5.0.7 on 2024-08-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='thumbnail_hover',
            field=models.ImageField(null=True, upload_to='thumbnail_hover_image'),
        ),
    ]
