# Generated by Django 5.0.7 on 2024-08-03 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_thumbnail_hover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant_images',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.product_variant'),
        ),
    ]
