# Generated by Django 5.0.7 on 2024-08-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_variant_images_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='colour_code',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='colour_name',
        ),
        migrations.DeleteModel(
            name='Product_variant_images',
        ),
    ]
