# Generated by Django 5.0.7 on 2024-08-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0002_useraddress_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
