# Generated by Django 5.0.7 on 2024-08-16 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_remove_product_variant_colour_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('house_name', models.CharField(max_length=500)),
                ('street_name', models.CharField(max_length=500)),
                ('pin_number', models.IntegerField()),
                ('district', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('country', models.CharField(default='null', max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(default='Order Placed', max_length=100)),
                ('payment_option', models.CharField(default='Cash_on_delivery', max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_id', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderaddress')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('main_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordermain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_variant')),
            ],
        ),
    ]
