# Generated by Django 5.0.7 on 2024-08-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermain',
            name='reason',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
