# Generated by Django 5.0.7 on 2024-09-04 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordermain_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordermain')),
                ('order_sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordersub')),
            ],
        ),
    ]
